name: jam_icons
description: Introducing the Jam Icons Flutter Package  Unlock a stunning collection of over 940 pixel perfect icons, ideal for a wide range of common actions and items.
version: 0.0.1
repository: https://github.com/Adiikust/Jam_Icons.git
homepage: https://github.com/Adiikust

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf